[package]
workspace = ".."
name = "day_2"
version = "0.1.0"
authors = ["auro"]

[dependencies]
packed_simd = "0.3.1"
ugly_array_decl = { path = "ugly_array_decl" }
galaxy_brain = { path = "galaxy_brain" }

[profile.release]
panic = "abort"
lto = true

[profile.bench]
lto = true